<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
<meta name="description" content="" />
<meta name="author" content="Christoph Rauscher" />
<link rel="author" type="text/plain" href="humans.txt" />
<title>Self / Digital Self — Bachelorarbeit von Christoph Rauscher</title>

<!--[if IE]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- STYLESHEETS -->
<link rel="stylesheet" type="text/css" href="css/reset.css">
<link rel="stylesheet" type="text/css" href="css/thesis.css">

<!-- JAVSCRIPT -->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=Fjalla+One|Noticia+Text:400,400italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

<script type="text/javascript">
      jQuery(document).ready(function($) {
        $(".scroll").click(function(event){
            event.preventDefault();
            $('html,body').animate({scrollTop:$(this.hash).offset().top}, 200);
        });
      });
  </script>

</head>

<body>
    <div id="container">
        
        <div id="content">

            <section id="zero">
                <a href="index.php"><h1>Self / Digital Self</h1></a>
                <p class="meta head">Im Rahmen meines Studienabschlusses im Fach <em>Interaction Design</em> habe ich mich mit der Selbstwahrnehmung im digitalen Raum befasst. Dabei ist die Bachelorarbeit <em>Self / Digital Self</em> entstanden. Betreuende Professoren und Dozenten: Prof. Cyrus Dominic Khazaeli, Lauritz Lipp. Berliner Technische Kunsthochschule. Christoph Rauscher &mdash; Berlin, Januar 2013.</p>
                <div class="clear"></div>
                <h2>Inhalt</h2>
                
                <div class="ihv_container">
                    <ol class="ihv" id="ihv_start">
                        <li><a href="#einleitung" class="scroll">Einleitung</a></li>
                        <li><a href="#begriffsklaerung" class="scroll">Begriffsklärung</a></li>
                            <ol class="layer_2">
                                <li><a href="#vernetzte-maschinen" class="scroll">Vernetzte Maschinen</a></li>
                                <li><a href="#veraenderung-der-schnittstellen" class="scroll">Veränderung der Schnittstellen</a></li>
                            </ol>
                        <li><a href="#interviews" class="scroll">Interviews</a></li>
                            <ol class="layer_2">
                                <li><a href="#stereotypen" class="scroll">Stereotypen des digitalen Zeitalters</a></li>
                                <li><a href="#selbstwahrnehmung" class="scroll">Selbstwahrnehmung des digitalen Ich</a></li>
                                <li><a href="#kommunikation" class="scroll">Kommunikation der Identität</a></li>
                                <li><a href="#fazit" class="scroll">Fazit: Schnittmengen und Gegensätze</a></li>
                            </ol>
                        <li><a href="#das-interface-als-uebermittler" class="scroll">Das Interface als Übermittler</a></li>
                            <ol class="layer_2">
                                <li><a href="#aussagen-der-teilnehmer" class="scroll">Aussagen der Teilnehmer</a></li>
                                <li><a href="#ideen-zum-interface-design" class="scroll">Ideen zum Interface Design</a></li>
                            </ol>
                        <li><a href="#schluss" class="scroll">Schluss: „Online“ als verbleichendes Präfix</a></li>
                        <li><a href="#literaturverzeichnis" class="scroll">Literaturverzeichnis</a></li>
                    </ol>
                </div>                
            </section>

            <section id="one">
                <div class="chapter">
                    <h2 id="einleitung">Einleitung</h2>
                </div>

                <p>Die Computer haben Einzug erhalten in das Leben der Menschen – mittlerweile viel sanfter, als die ruckelige Startphase es prophezeit hatte. Wir haben keine großen, schweren und grauen Maschinen mehr in unseren Arbeitszimmern stehen, und auch keinen HAL 9000 Roboter, der menschensgleich mit uns interagieren soll. Stattdessen hat sich die Computerintelligenz in unseren Alltag integriert – wir verlieren die Angst vor den Maschinen, erkennen Sinn und Unsinn der Technik und beginnen, sie emotional und selbstverständlich in unser Leben zu lassen.</p>

                <p>Diese Integration der Technik in den Alltag hat zur Folge, dass die Grenzen zwischen analogem und digitalem Raum verschmelzen – und gleichzeitig eine Umpositionierung unseres Selbst stattfinden muss. Der Standpunkt unserer Körper hat sich gewandelt von einem rein physischen zu einem virtuellen Aufenthaltsort. Mit diesem Wandel geht auch ein Wandel der Selbstwahrnehmung einher: Neue Orte beinhalten oftmals ein neues Identitätsverständnis, mit dem wir uns beschäftigen müssen. Versuchen wir, unser Identitätsbild eins zu eins in den digitalen Raum zu übertragen, oder besteht nach wie vor ein Bedürfnis nach Anonymität und Verfremdung? Unzählige neue, digitale Werkzeuge ermöglichen uns, die Auslegung der eigenen Identität zu kontrollieren und zu polieren, oder sind es schlussendlich womöglich die Maschinen, die unser Selbstbild verzerren?</p>

                <p>Dieser Text will nicht unbedingt Antworten finden auf philosophische Fragen und Ideen. Es soll vielmehr versucht werden, ein momentanes Stimmungsbild der aktuellen Situation wiederzugeben – wie sich die Bewohner des digitalen Raums wahrnehmen, online und offline, und ob sie überhaupt unterscheiden zwischen analoger und digitaler Identität. Um diese Momente aufzuzeichnen, habe ich sechs Interviews mit jungen Erwachsenen geführt (alle Gespräche sind in Dialogform als Anhang beigelegt). Anschließend wurden die Interviews ausgewertet und miteinander in Verbindung gebracht. Herausgekommen ist ein interessantes Portrait einer Generation, die einerseits technisch aufgeklärt ist, aber gleichzeitig emotional mit Technologie umgehen möchte. Thematisch bewegen wir uns vom Bewusstsein über persönliche Eigenschaften hin zur Projektion ebendieser in die Digitalität. Wir beschäftigen uns mit der Kommunikation des Selbst im Internet und schlussendlich mit dem Einfluss und der Rückwirkung, die Computer und technische Schnittstellen auf uns haben. Beginnen will ich mit einem Überblick, der uns helfen soll, den Handlungsort der Untersuchungen genauer zu erfassen.</p>
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>

            </section> <!-- // section 1 -->

            <section id="two">
                <h2 id="begriffsklaerung">Begriffsklärung</h2>

                <h3 id="der_digitale_raum">Der Digitale Raum</h3>

                <p>Um die Analyse in ihrer thematischen Vielschichtigkeit einzugrenzen und übersichtlich zu halten, müssen zu Beginn einige wesentliche Begriffe und Definitionen erläutert und festgelegt werden. Der Themenkomplex „Digitale Identität“ kann auf verschiedenen Ebenen ausgelegt und analysiert werden – beispielsweise auf den Ebenen der Sozialwissenschaft, der Kommunikationswissenschaft oder der Philosophie. Da der Schwerpunkt des Themenfeldes dieser Arbeit aber durch den Blickwinkel des Gestalters interaktiver Systeme aufgearbeitet werden soll, spielen im Hinblick auf die digitalisierende Umstrukturierung der Gegenwart besonders zwei Aspekte eine tragende Rolle: Der digitale Raum in seinen ersten Erscheinungsformen, seiner Verwandlung und seiner Bedeutung im Jetzt, sowie die Definition des Selbst in diesem in den digitalen Raum übertragenen Identitätsbegriffs.</p>

                <p>Der Begriff des „digitalen Raumes“ wurde innerhalb der vergangenen Jahre enorm gewandelt. Er entwickelte sich von einer reinen Utopie<sup><a id="footnote_1" href="#footnote_01">1</a></sup> zu einer Art Heterotopie<sup><a id="footnote_2" href="#footnote_02">2</a></sup>, und schließlich hin zu einer annehmbaren Realität, die schwer vom „analogen Raum“ zu trennen ist. Während es in den Anfängen des Internets, wie wir es heute kennen, kaum vorstellbar war, dass ein technisch vernetztes System zum Datenaustausch in unseren herkömmlichen, wenig digitalisierten Alltag integriert werden könnte, ist dieses Netz in seiner heutigen und auch in seiner zukünftigen Form aus unseren alltäglichen Strukturen der Verwaltung und Kommunikation nicht mehr wegzudenken. Dies hängt einerseits mit den Maschinen selbst zusammen, aber auch mit unserem Verständnis für unsere Umgebung, in der sich Digitalität und Analogität heutzutage zwangsweise vermischen.</p>

                <p>Marco Hemmerling beschreibt uns Computernutzer in den Anfängen der Virtualität als „Gefangene einer eingeschränkten Wahrnehmung der Wirklichkeit, auch wenn die digitalen Technologien es anders verheißen“ (Hemmerling 2011, 15). Diese Aussage macht Sinn, beruht allerdings auf der mittlerweile nahezu veralteten Wahrnehmung, die digitale Umgebung durch einen einzigen „Tunnel“ – beispielsweise durch einen Monitor hindurch – zu sehen. Erste direkte Übertragungen des virtuellen Raums (VR) in den physischen Raum passierten durch das Übergehen von Tunneln zu sogenannten CAVES. Diese Höhlen spielen auf die direkte Übertragung virtueller Räume in physische Räume an. Beispielhafte Schnittstellen hierfür sind etwa die Spielkonsolen Nintendo Wii und die Microsoft Kinect<sup><a id="footnote_3" href="#footnote_03">3</a></sup>. Erstere besteht aus einem Empfänger, der an die Konsole angeschlossen wird und über dem Display platziert ist, sowie einem Controller, der kabellos die Signale der vom Spieler ausgeführten Interaktionen an den Empfänger sendet. Ähnlich funktioniert die Kinect, die anhand von Infrarot-Technologie die Bewegungen der Spieler verarbeitet. Somit wird kein Controller mehr benötigt und die Schnittstelle zwischen virtuellem und physischem Raum wird transparent. Diese Transparenz hat sich bereits in das kollektive Bewusstsein der digitalen Generation eingeprägt und wird es auch noch in Zukunft verstärkt tun. Der Mensch projiziert sich nun ganz anders in die digitalen Umgebungen, als er es noch getan hat, als starre, komplexere Schnittstellen (bspw. Kommandozeilen in DOS-Systemen) üblich waren.</p>

                <p>Unvermeidlich scheint sich eine Trennlinie zwischen analogem und virtuellem Raum zu ziehen. Gleichzeitig wird diese Trennlinie durch die Digitalisierung des Alltags immer schwammiger. Hemmerling begründet diese Schwammigkeit mit der „allgegenwärtigen Datenpräsenz“, die für den Nutzer „ein subjektives Raumkontinuum, unabhängig von Ort und Zeit“ (Hemmerling 2011, 19) entstehen lässt. Hiermit ist vor allem das Dateimanagement gemeint, das sich von fest installierten Rechenzentren (Desktoparbeitsplätzen) auf mobile Endgeräte und darüber hinaus in die sogenannte Cloud – also Rechenzentren, auf die via Internet zugegriffen wird und die von selbst Daten synchronisieren – bewegt hat. Mark Weiser prägte hierbei den Begriff Ubiquitous Computing, also eine allgegenwärtige Computerisierung, bei der die Interfaces nicht mehr auf Screens beschränkt sind. Hierzu gehört beispielsweise auch die Augmented Reality, die von Ronald T. Azuma 1997 als „Kombination von realen und virtuellen Inhalten in einer realen Umgebung“ (ebd.: 20) definiert wird. Es entsteht folglich eine wirr erscheinende Mischung aus analogen, digitalen und halbrealen Inhalten, die auf eine bestimmte Art und Weise in einem Raum zusammen kommen sollen.</p>

                <p>Immer noch nicht geklärt ist nun jedoch der Begriff Digitaler Raum, der, wie eben erläutert, mit all seinen Bestandteilen und seinen Überlagerungen mit dem analogen Raum durchaus unscharf geworden ist. Paul Milgram entwickelte ein Modell, das er als „Reality-Virtuality-Continuum“ bezeichnet (vgl. Milgram 1994, 282–292). Hierbei wird zwischen einer realen Umgebung und einer virtuellen Umgebung unterschieden, die, je nach Gewichtung der jeweiligen Umgebung, eher real oder eher virtuell zu bewerten ist. Innerhalb dieses Systems nimmt die Virtualität allerdings nach wie vor eine unecht und künstlich wirkende Position ein – der „echten Realität“ wird schon allein durch den Begriff „real“ eine stärkere Bedeutung zugeschrieben. Zweifelsohne existieren die virtuellen Umgebungen, on- und offscreen, ebenso wie reale Umgebungen, und sind deswegen gleichzusetzen.</p>

                <p>Zusammenfassend und auf den verschiedenen Theorien aufbauend können digitale Räume als Umgebungen beschrieben werden, die durch Technologie erschaffen und in einem Gleichgewicht mit analogen Umgebungen zu positionieren sind. Hemmerling fügt beide Räume folgendermaßen zusammen: „Die erste Realität des physischen Raumes und die virtuelle Realität digital geschaffener Umgebungen verschmelzen zu einer emergenten Gesamterfahrung“ (Hemmerling 2011, 24). Durch diesen hybriden, emergenten Raum entsteht ein neues Projektionsfeld, das Platz und Entfaltungsmöglichkeiten bietet für unsere analoge(n) und digitale(n) Identität(en).</p>
                
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>

                <h3 id="identitaet_und_selbst">Identität und Selbst</h3>

                <p>Der Begriff „Identität“ eröffnet ein so komplexes und breites Themenfeld, dass seine Definition und Bedeutung für den hier vorliegenden Themenbereich des Interaktionsdesigns definiert und zugeschnitten werden muss. </p>

                <p>Grundlegend ermöglicht Identität in unserem heutigen Verständnis „soziales Handeln und interpersonale Interaktion“ (Misoch 2004, 18). Identität (vom lat. idem = das-, derselbe) beschreibt die Übereinstimmung von Eigenschaften zu dem Objekt oder Subjekt, das eben diese Eigenschaften verkörpert. In der Sozialwissenschaft setzt sich die allgemeine Identitätsvorstellung aus folgenden Bestandteilen zusammen: Einzigartigkeit, Kohärenz, Konstanz und Kontinuität (vgl. ebd., 20). All diese Bestandteile, insbesondere aber Letzterer, beziehen sich auf ein über einen andauernden Zeitraum hinweg konstant bleibendes Selbstbild als Grundvoraussetzung zu einer Identität. Die Frage »Wer bin ich?« kann nur durch ein Sich-Treubleiben beantwortet werden, da sonst keine eindeutigen Parameter zum eigenen Selbstbildnis festgelegt sind und die Identität stets undeutlich bleibt.</p>

                <p>In der analogen Realität kommt zum Begriff der Identität der Begriff des Selbst hinzu. Dieses Selbst ermöglicht diverse konzeptionelle Auslegungen der eigenen Identität: „Ein Mensch stellt verschiedene soziale und situative Identitäten dar, und er ist doch stets mit sich identisch. Er präsentiert verschiedene Arten des Selbst und verfügt zugleich über ein relativ stabiles Selbstkonzept“ (Mummenday 1995, 57). Diese Präsentation verdeutlicht den wichtigsten Entstehungsprozess eines Identitätsbilds: Selbstdarstellung ist eine Grundvoraussetzung zur Identitätsbildung – die Präsentation des Ichs ist die Bedingung des eigentlichen Ichs.</p>

                <p>Während wir in der analogen Realität also den Rahmen der Identität mit diversen Selbstbildern im Inneren zeichnen, verhält sich unser Bezug auf Identität und Selbst im digitalen Raum anders. Hinzu kommt die gesellschaftliche Transformation von Moderne zu Postmoderne, welche den Identitätsbegriff und die erforderliche Selbstpräsentation zusätzlich beeinträchtigt. </p>

                <p>Während der Begriff der Postmoderne erstmals im Jahre 1917<sup><a id="footnote_4" href="#footnote_04">4</a></sup> auftauchte (vgl. Misoch 2004, 68), spielt er auch zu Beginn des 21. Jahrhunderts eine tragende Rolle in Philosophie, Sozialwissenschaft, Architektur und Kunst. Er vereint „gesamtgesellschaftliche Erscheinungen der Heterogenisierung, der Pluralisierung, der Werteverschiebung sowie der Flexibilisierung und Individualisierung der modernen Kultur“ (vgl. ebd., 68). Das Internet, besonders in seiner heutigen sozialen Form, ist hierbei von großer Bedeutung – Selbstbilder, Selbstdarstellung und Selbstreflexion werden im Hinblick der stärkeren Individualisierung zunehmend relevant. Die Verschmelzung des analogen und des digitalen Raums erschafft eine neue Perspektive, um sich mit der postmodernen Identität im Kontext dieser neuen Räume zu befassen.</p>

                <p>Durch die gesellschaftlichen Umstrukturierungen der Postmoderne entwickelten sich Theorien, die dem Subjekt einen neuen Rahmen verleihen wollten. Einige Philosophen und Theoretiker gaben den Denkanstoß, sich aufgrund der enormen Disparität der Alltagswelt komplett von einem festgelegten Subjekt zu verabschieden. Während es sich vorher um eine einzige Identität mit diversen Selbstbildern handelte, wurde nun versucht, die Verbindung zwischen Subjekt und Identität aufzulösen. Es entstand die Idee eines „fragmentierten Selbstmodells“, beziehungsweise die Möglichkeit „multipler Identitätsentwürfe“ (vgl. ebd., 92f). Für die Entstehung eines Persönlichkeitsbildes, das trotz der gesellschaftlichen Umstrukturierungen zur Beantwortungen der Frage nach dem Ich relevant ist, entsteht die Idee einer „Bastelmentalität“ (Gross u.a. 1985), in der sich das Subjekt nicht mehr in einem starren Identitätsrahmen bewegt, sondern die Freiheiten der gesellschaftlich akzeptierten Individualisierung nutzt und sich seine Identität aus Bausteinen zusammen setzt. Ähnlich beschreibt es auch Sherry Turkle, die Identität als „ein Repertoire von Rollen, die sich mischen und anpassen lassen und über deren verschiedene Anforderungen verhandelt werden muss“ (Turkle 1998, 289) ansieht.</p>

                <p>Das Selbst wird also zum individuellen Begriff, das weder einer Norm noch einer Form entsprechen müsste. Das Internet als Raum erweiterte diese Freiheit im Bastelprozess durch diverse Faktoren, etwa die vielfältigen virtuellen Möglichkeiten der Zeit- und Raumüberschreitung und die vermeintliche Anonymität im Netz. Die „Handwerklichkeit“ dieser Identitätserstellung bekommt im Prozess der digitalen Selbstdarstellung (also in virtuellen Räumen, wie etwa sozialen Netzwerken oder MUDs<sup><a id="footnote_5" href="#footnote_05">5</a></sup>) eine besondere Haptik: Während im analogen Raum Identität zu einem großen Teil über den Körper geformt und sogar zur Identitätsverifizierung (bspw. Passfoto oder Fingerabdruck) genutzt wird (vgl. Misoch 2004, 22f), wird im digitalen Raum jeder Ausdruck der Selbstformung codiert. Sabina Misoch unterteilt die digitale Identität in vier Merkmale: Körperlosigkeit, textuelle Selbstrepräsentation, Bewusstsein und Simulationspotential (vgl. ebd., 130ff). Durch das Verschmelzen von analogem und digitalem Raum hebt sich aber beispielsweise die textuelle Selbstrepräsentation bis zu einem gewissen Grad auf – mit der rapiden Weiterentwicklung des Internets und seinen zunehmend emotional und intuitiv gestalteten Oberflächen ist Text nicht mehr Hauptmedium der (Ich-)Kommunikation. Bild und Bewegtbild nehmen eine zunehmende Rolle ein, während beispielsweise die Übersetzung realer Emotion in eine Computersprache (bspw. Emoticons oder Abkürzungen) abnimmt. Überaus wichtig sind allerdings Misochs Begriffe Bewusstsein und Simulationspotential – sie spielen mit innerhalb der heutigen Präsenz und Relevanz digitaler sozialer Netze eine immer größere Bedeutung.</p>

                <p>Identität im Internet ist also durch Postmoderne und Virtualität vielschichtig, aber nur bis zu einem gewissen Grad definierbar. Für die vorliegende Arbeit ist die Bausteinhaftigkeit der neuen (digitalen) Identität von besonderer Bedeutung, da sie die Übertragung des analogen Ichs in den emergenten Raum aus Realität und Virtualität besonders treffend beschreibt.</p>
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>
                
            </section> <!-- // section 2 -->

            <section id="three">
                <h2 id="beobachtungen">Beobachtungen</h2>

                <h3 id="vernetzte-maschinen">Vernetzte Maschinen</h3>

                <p>Beim Diskutieren und Nachdenken über die Erscheinung der digitalen Identität, besonders im Bezug auf Gestaltung von Schnittstellen, habe ich versucht, ein ganz grobes Prozessmodell mit den Komponenten Nutzer, Identität, Schnittstelle und Maschine zu erstellen, das mir und anderen erleichtern sollte, den Themenkomplex zu formen. Im Folgenden also ein paar grundlegende Überlegungen zur Selbstprojektion durch Maschinen:</p>

                <p>Bevor wir uns mit Identität und Interfaces beschäftigen wollen, müssen wir einen weiteren Schritt zurück treten und uns ein Bild der Szenerie machen: Der Prozess, in dem ein Mensch mit einem Computer interagiert, wird Human Computer Interaction, kurz HCI genannt. Dieser Prozess kann von Designern gestaltet und optimiert werden, um zu erfüllende Aufgaben möglichst einfach, angenehm und effektiv lösen zu können. Werfen wir einen Blick auf die Maschine, können wir unterschieden zwischen Maschinen, die für sich alleine stehen, und Maschinen, die an ein Netzwerk angeschlossen sind. Letztere können beispielsweise Computer oder Smartphones sein. Durch ihre Vernetztheit können sie unsere Eingaben an einen anderen Ort reflektieren, beispielsweise an einen anderen Computer, der von einem anderen Menschen benutzt wird, der nicht direkt mit uns in Kontakt steht. Ich denke, dass die Menge an Authentizität, die wir einem Computer preisgeben, davon abhängt, wie stark die Maschine mit einem Netzwerk verbunden ist und in wie weit wir als Nutzer das mitbekommen. Ein einfaches Beispiel hierfür ist die App <a href="http://dayoneapp.com/" target="_blank">Day One</a>, eine Tagebuch-Anwendung für Mac, iPad und iPhone. In ihr lassen sich einfach Fotos, Notizen und Erlebnisse festhalten. Die App ist mit einem Passwort verschließbar.</p>
                <figure>
                    <img class="dayone" src="media/dayone.png" alt="Day One App">
                    <figcaption>Das klassische Day One Interface in der Kalenderansicht.</figcaption>
                </figure>
                <p>Day One ist keine App, die für sich selbst steht: Sie ist ans Internet angeschlossen und tauscht die privaten Tagebucheinträge über das Internet mit allen gekoppelten Geräten aus. Dennoch ist der Zugriff privat; nur, wer die Anwendung mit dem entsprechenden Account nutzt und das Passwort kennt, kann die Daten einsehen. Ein privates Weblog ist anders strukturiert: Es ist so konzipiert, dass man private Gedanken teilt – sie sind von vornherein für die Öffentlichkeit bestimmt. In dieser Bestimmtheit wandelt sich die Projektionsfläche der Identität im digitalen Raum: Privatsphäre und Öffentlichkeit und die rein visuelle Offensichtlichkeit beider Faktoren spielen eine entscheidende Rolle beim Projektionsprozess. Um den momentanen Stand der Schnittstellengestaltung zur Projektionsfläche zu erläutern, will ich eine kurze Einführung in die für uns relevante Geschichte der graphischen Nutzeroberflächen geben.</p>
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>

                <h3 id="veraenderung-der-schnittstellen">Veränderung der Schnittstellen</h3>

                <p>Um den Einfluss technischer Schnittstellen auf unsere Projektion der eigenen Identität in digitale Umgebungen zu analysieren, müssen wir einen genaueren Blick auf diese Schnittstellen werfen. Im ersten Kapitel wurde kurz voraus gegriffen und mit der Wii und Microsoft Kinect zwei Interfaces genannt, die unseren momentanen Stand der Dinge gut skizzieren: Wir befinden uns in einem emergenten Raum, bestehend aus digitalen sowie analogen Erscheinungen, mit immer anwesenden und angeschalteten technischen Geräten. Der Alltag hat sich verwandelt in eine fast schon permanente Augmented Reality, angereichert mit digitalen Informationen, und erreichbar sowohl über digitale (on-screen) als auch analoge (off-screen) Oberflächen.</p>

                <p>Denken wir an die Bedienung der Computer in den 70er und 80er Jahren nach, erinnern wir uns beispielsweise an MS- und Apple-DOS-Systeme, die durch eine Command Line Shell – also einer verhältnismäßig einfachen Oberfläche zum Eingeben textueller Befehle – bedient wurden. Ein solches, via Kommandozeile gesteuertes Bedienungssystem wird heutzutage mit dem damaligen Stand der Hardware verbunden: Die Maschinen waren schwer, die Systeme waren wenig leistungsstark und langsam, und das Interface hatte generell kaum Gestaltung oder gar Persönlichkeit erhalten – und wurde deshalb auch wenig als Kanal für selbige genutzt. Dennoch fand textuelle Selbstformung anhand von ersten, befehlsgesteuerten Computerspielen statt – Sherry Turkle beschreibt in Leben im Netz die bereits erwähnten MUDs, in denen Computerspieler in verschiedene Rollen schlüpfen und – ähnlich wie in Second Life – miteinander interagieren und spielen, nur eben ausschließlich via Text (vgl. Turkle 1998, 11ff).</p>

                <p>Ändern sollte dieses rein auf Text und Kommandos basierende Schnittstellensystem das sogenannte Graphical User Interface (GUI), also eine Übersetzung der Kommandos in visuelle Metaphern. Das moderne visuelle Interface basiert grundlegend auf den WIMP-Komponenten (windows, icons, menus und point device). Zur Jahrhundertwende erlangte die Gestaltung dann einen weiteren Schub in Richtung Postmoderne: Dem Heimcomputer wurde eine neue Bedeutung geschenkt. Es wurde ein größeres Augenmerk auf Produktdesign gelegt, und die graphische Oberfläche der Betriebssysteme veränderte sich maßgeblich. Die mit der zehnten Version des Systems „Mac OS“ von Apple eingeführte Benutzeroberfläche Aqua revolutionierte die Art und Weise, wie bis heute digitale Interfaces gestaltet werden: Die Icons waren fast fotorealistisch umgesetzt, der Schreibtisch (Desktop) verstärkte seine Analogien zum realen Schreibtisch, auf dem der Computer stand, und die Rechner selbst fügten sich durch emotionales Design nahtlos in unsere alltägliche Umgebung ein. Mittlerweile spricht man von Skeumorphismus – also der Übertragung dreidimensionaler oder zumindest analoger Artefakte wie etwa Ledertexturen, metallene Schaltknöpfe und Holzoberflächen auf digital zweidimensionale Ebenen. Diese Art der Interface-Gestaltung ist umstritten, da sie prinzipiell versucht, den analogen Raum im digitalen Raum nachzuahmen, und nicht darauf hinarbeitet, eine neue Umgebung zu erschaffen – somit also zweitklassig bleibt. </p>

                <p>Diese ersten Anzeichen der „Fügung“ der Computer in unseren Alltag haben sich bis heute potenziert. Mittlerweile nehmen wir die Computer nicht mehr wahr – vielmehr noch nehmen wir es sogar verstärkt war, wenn etwas nicht computerisiert und technisiert ist; wenn der Computer fehlt, erscheint uns das komisch, manchmal sogar unvollständig. Nicht-computerisierte Prozesse wirken oft starr, mittelalterlich und unzufriedenstellend. Wir sehen den Computer als Teil unseres Alltags, und wir sehen uns als interagierende Kommunikationspartner mit dem Computern als Teil des Interfaces. Überspitzt wird diese Fügung durch die genannten Schnittstellen, die unsichtbar werden – Interfaces, die drahtlose Technologien verwenden und uns dennoch Zugang zu einer technischen Infrastruktur geben, werden immer relevanter. David J. Bolter und Richard Grusin geben dem Phänomen einen Begriff: Immediacy. In ihrem Buch Remediation schreiben sie: „The logic of immediacy dictates that the medium itself should disappear and leave us in the presence of the thing represented“ (Bolter und Grusin 1999, 6). Sie stellen folglich fest: Im Sinne der Immediacy ist das vermittelnde Medium dafür bestimmt, zu verschwinden und den Betrachter mit dem medial übermittelten Objekt in eine direkte Verbindung zu setzen. Es handelt sich folglich um ein Medium in der Erscheinung eines durchsichtigen Fensters, das uns nicht in sich selbst spiegelt, sondern in einen direkten Kontakt mit dem zu Betrachtenden setzt. Der Ort, in den wir uns während dieser transparenten Übermittlung bewegeben, ist nicht direkt begrenzt.</p>

                <p>Uns selbst an diesen „Zwischenort“, oszillierend zwischen Interface und analogem Raum, zu positionieren, ist nicht unbedingt einfach und erfordert teilweise ein hohes Maß an technischem Verständnis und Selbstreflexion. Aus diesem Grund habe ich mich für diese Analyse mit sechs jungen Menschen im Alter von 19 bis 26 Jahren zu den Themen Selbstwahrnehmung, Internetnutzung, Kommunikation und Sicherheit unterhalten. Im Folgenden möchte ich die Ergebnisse der einzelnen Gespräche vergleichen, auswerten und die besonderen Schnittmengen und Gegensätze markieren. Denn obwohl alle Interview-Partner der gleichen Generation – den Digital Natives – angehören, unterscheiden sich manche Aussagen maßgeblich.</p>
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>
            </section> <!-- // section 3 -->

            <section id="four">
                <h2 id="interviews">Interviews</h2>

                <h3 id="stereotypen">Stereotypen des digitalen Zeitalters</h3>

                <p>Anhand einer Sinus-Milieu-Studie des „Deutschen Instituts für Vertrauen und Sicherheit im Internet“ (DIVSI) wurde versucht, die diversen Generationen und Nutzergruppen des Internets zu sortieren. Es wird zwischen drei Hauptgruppen unterschieden: Die älteste Generation wird als Digital Outsiders benannt und in die Gruppen Internetferne Verunsicherte und Ordnungsfordernde Internetlaien unterteilt. Sie nutzen digitale Medien kaum und sind extrem skeptisch und teilweise auch verängstigt, was das Internet angeht. Die zweite Gruppe, Digital Immigrants, vertritt die Verantwortungsbedachten Etablierten und die Postmateriellen Skeptiker – also Menschen, die Computertechniken als Erwachsene erlernt haben und dem Internet generell kritischer gegenüberstehen. Die jüngste Generation, die Digital Natives, unterteilen sich wiederum in drei Gruppen: Die unbekümmerten Hedonisten, die effizienzorienterten Performer und die digitalen Souveränen. Schon in der Betitelung der Gruppen lässt sich erahnen, dass die jeweilige technische Affinität steigt und die Gruppe der digitalen Souveränen ein großes technisches Interesse und demnach auch eine hohe Internetnutzung aufweist.</p>

                <p>Für meine Interviews habe ich drei junge Männer und drei junge Frauen befragt, die ausschließlich den Digital Natives angehören. Bei der Auswahl der Interviewpartner habe ich versucht, die Personen so zu mischen, dass sich alle mit verschiedenen Untergruppen identifizieren können. Da ich im Folgenden viel aus den Gesprächen zitieren werde, möchte ich die Teilnehmer kurz vorstellen:</p>

                <p><strong>Paul,</strong> 23, arbeitet in einer Werbeagentur und bezeichnet sich selbst als „Nerd“ oder „Internetmensch“. Er ist sehr offen für neue Technologien und das Internet, und sieht sich als digitaler Souveräner.</p>

                <p><strong>Juliane,</strong> 19, ist journalistisch aktiv und studiert Kulturwissenschaften. Sie ist generell kritisch, was Technologien angeht, aber offen für Neues. Wie Paul sieht sie sich als digitale Souveräne.</p>

                <p><strong>Ann-Kathrin,</strong> 22, studiert Philosophie, Kunstgeschichte und Musikwissenschaft und ist sehr vorsichtig, was ihre Erscheinung im Netz betrifft. Sie sieht sich zwischen den effizienzorientierten Performern und digitalen Souveränen.</p>

                <p><strong>Dominic,</strong> 26, ist aktiver Videospieler und arbeitet beim deutschen Jugendschutz. Er nutzt das Internet gerne und unbesorgt und sieht sich wie Ann-Kathrin im Bereich der effizienzorientierten Performer und digitalen Souveräne.</p>

                <p><strong>Miriam,</strong> 21, studiert visuelle Kommunikation und sagt, dass ihre Selbstpräsentation im Netz wieder abgenommen hätte. Sie sieht sich am unteren Schnittpunkt der unbekümmerten Hedonisten, digitalen Souveränen und effizienzorientierten Performern.</p>

                <p><strong>Jan-Christopher,</strong> 22, studiert Informatik und hat ein großes technologisches Verständnis. Er positioniert sich, ähnlich wie Miriam, zwischen den unbekümmerten Hedonisten und digitalen Souveränen.</p>

                <p>Interessanterweise lag ich folglich mit meiner Einschätzung, was die Milieus angeht, falsch: Jeder Teilnehmer bekam die Milieu-Studie zu sehen und im Gesamtbild ordneten sie sich alle in sehr dicht aneinander liegende Bereiche ein:</p>
                <figure>
                    <img class="sinus" src="media/sinus.png" width="716" height="420" alt="Sinus">
                    <figcaption>Die Sinus-Milieus der DIVSI-Studie. Grafik: <a href="https://www.divsi.de/" target="_blank">www.divsi.de</a></figcaption>
                </figure>
                
                <p>Die Fragen, die ich den Teilnehmern gestellt habe, untergliederten sich in vier thematische Bereiche: Im ersten Teil wurden mir Fragen zum Thema Digitale Identität und Selbstpräsentation im Internet beantwortet. Damit wollte ich grundlegend herausfinden, in wie weit meine Teilnehmer überhaupt schon über ihr Selbstbild im Internet reflektiert haben, und wie es ihr Aufwachsen mit digitalen Medien beeinflusst haben könnte. Der zweite Teil beschäftigte sich mit der Digitalisierung des Alltags – so konnte ich mir ein genaueres Bild der technischen Versiertheit meiner Interviewpartner machen. Im dritten und vorletzten Teil habe ich detaillierte Fragen zur Kommunikation durch digitale Kanäle gestellt, und der letzte Teil beschäftigt sich mit dem Thema Sicherheit und Bewusstsein. Dort ging es mir darum, herauszufinden, wie weit sich die Teilnehmer überhaupt von Technik und Algorithmen einnehmen lassen. Außerdem habe ich mit allen Teilnehmern eine Assoziationskette gemacht: Zu jeweils 28 Begriffen sollten sie den ersten Gedanken nennen, der ihnen in den Sinn kam:</p>
                
                <p><a href="media/assoziationskette.pdf">&rarr; Assoziationskette herunterladen (PDF, 127KB)</a></p>
                
                <p>Gleichfarbige Zellen beinhalten gleichwertige Aussagen, wobei hier in grün und orange unterteilt wurde. Blau markierte Zellen heben besonders interessante und bemerkenswerte Aussagen hervor. Gedankenstriche bedeuten eine Auslassung des Begriffs. Die Matrix zeigt, dass einige Gedankensprünge innerhalb des Themenkomplexes oft vorkommen, wie etwa Sicherheit, Relevanz des Datenschutzes und eine generelle Begeisterung für Technik. Andererseits stehen manche Begriffe in einem gewissen Gegensatz zueinandner: Während beispielsweise Paul beim Wort Anonym sofort an Scientology denkt, ist es für Ann-Kathrin Sicherheit. Die assoziierten Begriffe sollen helfen, sich ein erstes Bild der jeweiligen Interviewpartner zu verschaffen.</p>

                <p>Die Aufarbeitung der entstandenen Gespräche sieht im Folgenden so aus: Zu erst will ich beschreiben, wie die jeweiligen Teilnehmer mit dem Thema Identität und folglich auch digitaler Identität umgehen. Dort werde ich zusammenfassen, wie die Selbstwahrnehmung der Generation der Digital Natives aussieht, und wie sie sich ins Internet überträgt – sie ist nämlich breit gefächert von Emotionen wie Vorsicht, Nachdenklichkeit und Angst, bis hin zu absoluter Weltoffenheit, Verspieltheit und Sorglosigkeit.</p>

                <p>Der zweite Teil der Aufarbeitung versucht anschließend, diese Selbstwahrnehmung auf Kommunikation durch digitale Medien zu übertragen: Welche Werkzeuge und Interfaces beeinflussen unsere Kommunikationsgewohnheiten? Welche Vor- und Nachteile sehen die Befragten in digitaler, beschleunigter Kommunikation, und welche Rolle spielt Authentizität dabei?</p>
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>
            </section>

            <section id="five">
                <h3 id="selbstwahrnehmung">Selbstwahrnehmung des digitalen Ich</h3>

                <p>„Im Großen und Ganzen glaube ich, dass ich (online) genau so bin wie im normalen Leben.“ Das sagt Paul über sein Identitätsbild, das er von sich selbst im Netz zu erschaffen versucht. Das ist auch der Konsens, den die meisten der Interview-Partner teilen: Es wird nicht versucht, ein fremdes oder bestimmten Regeln entsprechendes Selbstbild zu skizzieren und im digitalen Raum zu verkörpern, sondern generell wird Wert auf Echtheit gelegt. Dominic stellt aber fest, das Identitätsbild im Internet eröffne eine Sehnsucht, die jeder ein bisschen ausleben möchte – die virtuelle Welt will genutzt werden, um mal jemand anderes zu sein und in eine neue Rolle schlüpfen zu können. Er persönlich nutze dafür aber eher die Welt der Videospiele.</p>

                <h4 id="rollen_und_authentische_rollen_im_netz">Rollen und authentische Rollen im Netz</h4>

                <p>Jedes Interview habe ich mit der Frage nach ersten eigenen E-Mail-Adressen und frühen Nicknames begonnen. Schon dabei wird deutlich: Fünf von sechs Befragten haben in ihrer ersten E-Mail-Adresse ihren Klarnamen oder, wie etwa Juliane, den Familiennamen für eine gemeinsam genutzte Adresse verwendet – es deutet also bereits hier wenig auf den Wunsch nach direkter Neuschaffung der Identität hin. Nicknames waren nur in ganz anfänglichen Phasen der persönlichen Internetnutzung im Gebrauch: Etwa für Online-Foren auf Kindernetzwerken oder in Videospielen. Diese erfundenen Namen waren etwa schmedderfly (Juliane: „Ich wollte etwas Kreativeres als alle anderen; nichts mit Sternchen und Zahlen, wie das angesagt war. Schmetterlinge waren wohl meine Lieblingstiere.“), p4aulchen (Paul verwendet generell seinen Klarnamen, weicht aber auf eine Buchstaben-Zahlenkombination aus, wenn „Paul“ oder „Paulchen“ schon vergeben sind), Frau Katze (Miriam war als Teenager auf MySpace aktiv und hat die Plattform genutzt, um ihr Selbstbild intensiv zu formen und dadurch auch neue Kontakte zu knüpfen), oder dr_prosecco und mulucirruc (Dominics erste E-Mail-Adresse und Nickname, bevor er in sozialen Netzen Varianten seines Klarnamens verwendete).</p>

                <p>Alle Aussagen zu Nicknames und der anfänglichen Internetaktivität auf Kindernetzwerken (beispielsweise des Ki.Ka oder in Foren von Musiker-Fansites), wie das anschließend schnell normal gewordene Nutzen des Klarnamens beschreibt gut, wie sich die Generation der Digital Natives ins Internet übertragen möchte: Man will niemand Fremdes spielen, sondern sich selbst – bis zu einem gewissen Grad – online vertreten. Sherry Turkle beschreibt noch Ende der 1990er Jahre ein gegenteiliges Phänomen: Die Nutzer der MUDs suchen den digitalen Raum und die virtuelle Spielwelt aus dem gegengesetzten Grund auf: Sie genießen es, in fremde Rollen zu schlüpfen und andere Identitäten, auch parallel, anzunehmen (vgl. Turkle 1998, 16). Mein Interviewpartner Paul, der in seiner frühen Jugend auch viel Zeit mit Computerspielen verbracht hat, erwähnt: „Es gibt ja auch genug bärtige Männer, die bei World of Warcraft Frauen oder Elfen spielen, weil sie einfach lieber hübsche Frauen steuern als sich selbst in Form kleiner Zwergencharakter.“ Dieses In-fremde-Rollen-schlüpfen ist also großteils in die Welt der Computerspiele verschwunden, und wird dort auch wenig mit der eigenen Persönlichkeit in Verbindung gebracht. Ein (geheimes) Zweitprofil hat niemand – Paul hat lediglich zu Testzwecken von selbst entwickelten Anwendungen seiner Agentur einen Facebook-Testaccount: „Ich wollte nicht, dass das in meinem privaten Facebook-Account sichtbar ist.“</p>

                <h4 id="eigenschaften_der_analogen_identitt">Eigenschaften der analogen Identität</h4>

                <p>Als ich die Teilnehmer fragte, ob sie ihre analoge Identität in einigen Eigenschaften beschreiben könnten, waren sich drei Teilnehmer sehr sicher und konnten ihren Charakter gut bündeln, die anderen drei zögerten: Dominic beispielsweise versuche immer, sein Selbstbild und sein Fremdbild sehr kongruent zu halten, deswegen wollte er sich nicht auf Begrifflichkeiten festlegen. Ann-Kathrin findet: „Fremdwahrnehmung und Eigenwahrnehmung gehen ja generell sehr weit auseinander, und Sprache erzeugt dabei sehr viele Missverständnisse.“ Auch Miriam war der Meinung: „In zwei Tagen würde ich vermutlich etwas ganz anderes sagen“. Besonders bei Miriams Aussage kann eine Verbindung zu Turkles Theorie des „Rollen-Repertoires“, das in verschiedenen sozialen Kontexten flexibel einsetzbar ist, gemacht werden.</p>

                <h4 id="bertragung_der_eigenschaften">Übertragung der Eigenschaften</h4>

                <p>Beim Übertragen der jeweiligen Eigenschaften des analogen Ich hin zu digitalen Identität stellte sich heraus, dass die Arten und Weisen der Übertragung nicht unbedingt bewusst von statten gehen. Miriam bemerkt, dass sie seit dem Ende ihrer Aktivität auf MySpace sowieso nicht mehr so emsig an ihrem Internetbild arbeite, aber generell darauf achte, dass ihre schriftliche Kommunikation – also ihr Schreibstil in E-Mails, SMS und Nachrichten – ihrer mündlichen Kommunikation sehr entspreche. Auf die Kommunikationsformen werde ich im folgenden Teil noch genauer eingehen. Zur Übertragung der Eigenschaften kristallisiert sich allerdings ein gemeinsamer Konsens heraus, den Juliane schön beschreibt: „Ich schließe zumindest bestimmte Teile meiner Identität (online) aus. Beispielsweise den Teil von mir, der mich zeigt wie ich zu Hause vor meiner Familie oder meinen Großeltern bin. Manchmal kommentiert meine Oma auf Facebook meine Updates, das ist mir unglaublich peinlich. Dieses Ausschließen mache ich auch absichtlich, denn ich würde ja auch nicht jedem meine Oma vorstellen.“ </p>

                <p>So gehen die meisten vor – bewusst und unbewusst –, was die Projektion ihres Selbstbilds betrifft: Bestimmte Identitätsmerkmale bleiben dem digitalen Raum generell verschlossen; andere werden nur mit einer kleinen Gruppe oder einem bestimmten Netzwerk geteilt; manches wird allen öffentlich gemacht. Die Gründe dieser Auswahl sind verschieden: Manchen ist die Privatsphäre im Netz so wichtig, dass sie sich scheuen, zu viele Informationen oder gar Charaktereigenschaften verfügbar zu machen – anderen scheint das mittlerweile so stark gewachsene Datennetz so unübersichtlich, dass sie relativ unbesorgt sind, was ihre Daten und damit ihr Erscheinen im digitalen Raum betrifft.</p>

                <h4 id="die_digitale_quintessenz">Die digitale Quintessenz</h4>

                <p>Auch das generelle Bewusstsein der Netz-Identität abseits der direkten Übertragung ist verschieden ausgeprägt: Ein Teil der Befragten empfindet ihr Identitätsbild im Netz wesentlich verstreuter als offline. Paul sagt: „Ich (bin) im digitalen Raum verstreuter, zumindest im Sinne der digitalen Profile. Im realen Leben konzentriere ich mich mehr auf meine eigene Person.“ Auch Jan-Christopher empfindet es so: „(Im Internet) können nie alle Seiten von mir herauskommen. Offline, im hier und jetzt, kann ich ja nur Ich sein. Im Internet kann man eine bestimmte Sache zurückhalten.“ </p>

                <p>Die Mehrheit aber, vier von sechs Befragten, empfinden sich und ihre Identität im digitalen Umfeld konzentrierter. Juliane führt ihre digitale Kanalisierung auf das Organisieren der sozialen Kontakte zurück: „Vorher war meine Persönlichkeit im Internet viel zerstreuter, und nachdem ich bei Facebook meine Kontakte in ordentliche Listen sortiert habe und in meinem Blog mein Leben sammle, ist das Internet eine Art Sammelpunkt für meine verschiedenen Lebensbereiche.“ Juliane geht es dabei weniger um den Schutz ihrer Privatsphäre, als viel mehr um das eigene Bewusstsein dafür, wer mit ihr über digitale Knotenpunkte verbunden ist und wie weit ihr Netzwerk reicht. So kann sie durch ihre Selbstkenntnis leichter einschätzen, zu welchen sozialen Kreisen hin sich ihr Selbstbild kanalisiert. Auch Dominic und Miriam fühlen sich durch die digitalen Kanäle – wie etwa soziale Netzwerke, Blogs und Videospiele – in ihrer Selbstpräsentation direkter gesammelt. Ann-Kathrin, der die Anonymität im Internet sehr wichtig ist, illustriert ihre Position mit einem Beispiel: „Im Digitalen bin ich gebündelter, weil ich dort eine größere Kontrolle habe über das, was ich von mir veröffentliche. Wenn ich einen Raum betrete, kann ich niemanden davon abhalten, mir ins Gesicht zu gucken – auf Facebook kann ich das ganz einfach, indem ich kein Foto von mir hochlade.“ Nimmt man anhand dieser Illustration Bezug zur Interface-Theorie, ist interessant festzustellen, dass Ann-Kathrin die Maschine – in ihrem Fall Facebook – als Schnittstelle nutzt, um eine direktere Schnittstelle, nämlich das Erkennen und Identifizieren des Gesichtes durch Andere, zu unterbinden. Sie versteckt sich förmlich hinter dem von ihr undurchsichtig gemachten Interface. Bezogen auf die Theorie von David J. Bolter und Richard Grusin (1999) transformiert sie die Immediacy zur Hypermediacy, also zur absoluten Sichtbarkeit des Mediums – hier Facebook – selbst.</p>

                <p>Der langen Rede kurzer Sinn wird von meinem Interview-Partner Paul mit der Erkenntnis erfasst: „Manchmal hat man (online) sozusagen eine digitale Quintessenz von sich selbst.“ Er bezieht sich darauf auf seine generelle Verstreutheit im Netz – Er nutzt unzählige Social Media Kanäle, die aber im Grunde alle nur das beinhalten, was er auch wirklich dort veröffentlicht. Beim Nutzen der Kanäle sind wir sozusagen unterbewusst bewusst am Sortieren und Organisieren unserer Selbstwahrnehmung – alles, was wir als Baustein unserer Ich-Präsentation mit aufnehmen wollen, wird dem digitalen Raum (breit oder weniger breit gefächert) zur Verfügung gestellt.</p>

                <h4 id="rckprojektion_des_netzes">Rückprojektion des Netzes</h4>

                <p>Während wir uns also unbewusst bewusst ins Netz projizieren, projiziert es auf zwei Weisen auf uns zurück. Bei den Gesprächen konnte ich eine interessante Beobachtung machen: Die Teilnehmer beschäftigte nicht nur ihr eigener Input in digitale Medien und Identitätsentwürfe, sondern auch der Output, also die direkten und indirekten Folgen der Selbstdarstellung. Auf die Frage nach Vorteilen der digitalen Identität antworteten fast ausschließlich alle mit dem Fakt, dass sich ihre Kontakte und Freundeskreise ernsthaft (nicht nur in Form der Freundesanzahl auf Facebook) erweitert hätten und sie auch einen weiteren Blick über die Dinge, etwa durch schnellstmögliche Websuchen, erhalten hätten. Juliane denkt über ihre frühe Nutzung des Internets nach: „Seit ich 13 oder 14 bin, spielt das Finden von Sachen im Internet eine große Rolle. Diese Verfügbarkeit von Informationen hat mich und meine Interessensgebiete sehr geprägt. Ich habe immer nach Inspiration gesucht von Dingen, die nicht in meinem direkten Umfeld waren.“ Paul hat über Twitter seine Wohnung und seinen Ausbildungsplatz, also sehr konkrete Dinge, gefunden und erreicht. Für ihn ist auch der Kontakt auf Twitter mit Leuten, die er kaum kennt, interessant: „Wenn man etwas bei Twitter postet, und man sofort direktes Feedback bekommt, auch von Leuten, die man gar nicht wirklich kennt, dann ist das eine ganz überraschende und coole Form von Bestätigung.“</p>

                <h4 id="daten_dna_und_algorithmen">Daten-DNA und Algorithmen</h4>

                <p>Parallel werden durch Algorithmen Datenprofile der Nutzer erzeugt, die bis zu einem gewissen Grad einer biologischen DNA ähneln. Ich habe mit meinen Teilnehmern viel über Sicherheitsbewusstsein und Datenschutz gesprochen – mit dem überraschenden Ergebnis, dass alle Teilnehmer sehr aufgeklärt sind, was die Technologien angeht, und gleichzeitig sehr abgeklärt, was den persönlichen Datenschutz betrifft. Was beispielsweise Google über sie speichert, stört sie in gewisser Weise – andererseits wollen sie die Zuverlässigkeit der Ergebnisse nicht missen und kaum jemand nutzt ernsthaft alternative Suchmaschinen. Die Personalisierung der Suchresultate ist vielen ein Dorn im Auge: Miriam meint: „Ich glaube nicht, dass ich so durchschaubar bin, als dass es mir das Leben besser oder leichter machen könnte.“ Auch Juliane geht es so: „Ich glaube, ich bin zu divers, um personalisiert zu werden.“ Den meisten ist nicht bewusst, dass Google gerade durch angepasstes Filtern der Ergebnisse meist eindeutige Resultate erzielt. Dieses unsichtbare Zurückwerfen der Identitätsbausteine – etwa in Form von Sucheinträgen – bleibt also für einen Großteil der Nutzer unsichtbar, und wenn es bemerkt wird, eher negativ im Bewusstsein.</p>

                <p>Wir sprechen also, mal mehr mal weniger bewusst, mit Maschinen, die das von uns geformte Selbstbild in sich aufnehmen und dadurch gegebenenfalls auch rückprojizierend auf unsere Identität einwirken. Die Online-Identität kann durch digitale Kanäle entweder gestreut oder extrem gebündelt werden – je nach dem, wie bewusst wir unsere Eigenschaften dafür filtern. Dieses Filtern will ich im Bezug auf die Kommunikation des Selbst gegenüber Maschinen (Oberflächen) und Mitmenschen im Folgenden Teil nochmals genauer analysieren.</p>
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>
            </section>

            <section id="six">
                <h3 id="kommunikation">Kommunikation der Identität</h3>

                <p>„Ich (bewege) mich nicht mehr nur in einem Raum mit mir selbst, sondern in einem Kommunikationszusammenhang.“ Dieses Gefühl beschreibt Ann-Kathrin, wenn sie ihr Handeln im digitalen Umfeld reflektiert. Bei der Identitätsgestaltung und -kommunikation im Web handelt es sich, wie bereits beschrieben, um zwei Dialoge: Der eine findet zwischen Mensch und Maschine statt, beinhaltet also alle Informationen, die wir den Netzwerk durch eine Oberfläche vermitteln. Der zweite Dialog wirkt umgekehrt in Form einer Maschine-Mensch-Kommunikation, in der die Oberflächen auf uns zurück wirken und uns im ersten Dialog-Part beeinflussen.</p>

                <h4 id="digitale_verfgbarkeit">Digitale Verfügbarkeit</h4>

                <p>Diese beiden Dialoge sind grundlegend gekoppelt an den Grad der Verfügbarkeit, die wir von uns im digitalen Raum bereitstellen. Mein Interviewpartner Paul, der auf vielen sozialen Netzwerken aktiv ist, stellt fest: „Man könnte sich vermutlich ein gutes Bild von mir machen, wenn man einfach allen Accounts von mir folgt. Dann wüsste man wohl, was für ein Mensch ich bin.“ Durch die Streuung seiner Identität auf diverse Kanäle macht er sich zwar in großem Umfang verfügbar; sein digitales Ich kann aber nur erfasst werden, wenn alle Kanäle in gleichem Maße betrachtet werden. Als Schnittstelle kann hierfür die Funktion des „Folgens“ – Follow – aufgeführt werden, die mittlerweile in den meisten sozialen Netzwerken vorhanden ist. Auf Twitter und Facebook können öffentliche Updates „abonniert“, also verfolgt werden, die von Interesse sind. Auch auf Tumblr oder visuellen Netzen wie dem Fotoservice flickr oder instagram wurde die Freundschafts-Verbindung ersetzt durch einen Follow-Button, der nicht mehr voraussetzt, persönlich mit dem jeweiligen Person bekannt zu sein. Automatisch macht man sich dadurch einem breiteren Personenkreis verfügbar.</p>

                <p>Dieses Sich-verfügbar-machen beginnt aber schon bei der eigenen Beobachtung der Auffindbarkeit des Selbst im Netz. Die meisten meiner Interviewpartner googlen sich regelmäßig. Ann-Kathrin beispielsweise achtet sehr auf ihr Erscheinen in Suchmaschinen: „Ich habe Fotos von mir entfernen lassen, auf denen ich zu erkennen war, und wo zum Teil mein Klarname direkt damit verbunden war. (…) Generell möchte ich nicht visuell googlebar sein.“ Diese Konsequenz, die Ann-Kathrin mit ihrem digitalen Selbstbild pflegt, ist im Vergleich zu meinen anderen Interviewpartnern sehr streng. Die meisten achten lediglich darauf, dass die Inhalte, die von Suchmaschinen gefunden werden, sie mindestens neutral und bestenfalls positiv darstellen. Paul bemerkt sogar, er fände es komisch, wenn Leute ganz streng mit ihrer digitalen Erscheinung seien. Partyfotos, auf denen er schlimm aussehe, würde er zwar entfernen lassen, aber so wenig zu sich selbst zu stehen fände er nicht nachvollziehbar.</p>

                <p>Die Google-Suche als Schnittstelle ist ein interessantes Beispiel dafür, wie die unbewusste Formung des digitalen Ichs durch die Öffentlichkeit des digitalen Raums rückprojiziert werden kann. Der Medienkünstler Johannes P. Osterhoff hat die Grauzone der Privatsphäre genutzt, um eine einjährige Performance namens <a href="http://google.johannes-p-osterhoff.com/" target="_blank">„Google“</a> zu starten: Sämtliche Suchbegriffe, die er auf seinem Telefon, Netbook, Laptop und Arbeitsrechner mit Enter bestätigt, werden auf einer Website gelistet und sind für alle nachvollziehbar. Das öffentliche Googlen dreht den privaten Vorgang des „Anvertrauens“ einer Frage an die Suchmaschine, die für uns lediglich als Computer und lebloses Wesen wahrgenommen wird, um und macht aus der privaten, unbewussten Selbstprojektion (in diesem Fall innerhalb der Suchmaschine) ein öffentlich geltendes Statement.</p>
                
                <figure>
                    <img class="google" src="media/google_osterhoff.png" alt="Google by Johannes P. Osterhoff">
                    <figcaption>„Google“ von Johannes P. Osterhoff (Performance vom 1. 1. bis 31. 12. 2011)</figcaption>
                </figure>
                
                <h4 id="aktivitt_intensitt_und_positionierung">Aktivität, Intensität und Positionierung</h4>

                <p>Wie zu Beginn schon festgestellt, bedingt Identität irgendeine Form der Selbstdarstellung. Ohne sie kann gar kein Selbstbild geformt werden. Entscheidend hierfür ist die Intensität der eigenen Projektion: Vergleichbar mit der Stärke einer Glühlampe im Projektor kann unterschieden werden, mit welcher Intensität die Netzwerkteilnehmer sich selbst projizieren. Ein gutes Beispiel dieser Theorie ist Miriam: Sie hat, wie bereits beschrieben, kein großes Bedürfnis mehr, ihr digitales Selbstbild zu pflegen. Sie hat versucht, durch ein eigenes Tumblr Blog im Netz präsent zu sein – „Irgendwie habe ich mich mit dem Blog aber nie so richtig positioniert – ich wusste nicht, ob es ein persönliches Blog oder ein Portfolio-Blog sein sollte, oder alles zusammen, und wegen dieser Inkonsequenz habe ich wieder aufgehört.“ Wogegen sie auf MySpace als Teenager sehr aktiv war: „Bei MySpace habe ich mein Profil total gepflegt (…) und meine Über-Mich-Sektion ausgeschmückt (…). Ich hab das auch noch und gucke da manchmal gerne drauf. Irgendwie will ich die Seite nicht löschen.“</p>

                <p>Miriams Problem war also, dass sie das Gefühl hatte, sich mit zunehmendem Alter auch zunehmend positionieren zu müssen. Ann-Kathrin positioniert sich auf Facebook ganz bewusst mit ihrer Anonymität: „Natürlich ist mein Profil total konstruiert; ich habe nur Schwarzweißfotos hochgeladen.“ Sie versuche eher, sich selbst durch Visuelles, was sie interessiert oder womit sich sich identifiziert, zu übertragen. Ihre Verhaltensweise auf Netzwerken wie Facebook passiert unter dem Aspekt, dass sie es weit wie möglich von sich frei halten möchte und hauptsächlich als Werkzeug zur Kommunikation mit anderen, nicht des eigenen Ichs, nutzt.</p>

                <p>Was das Teilnehmen an der Projektion angeht, ist Paul mit seinen zahlreichen Accounts sicher der online aktivste Teilnehmer der Interviewreihe. Sein Haupttool, um sich im Netz verfügbar zu machen, ist Twitter: „Twitter ist wie ein Strom, in den man bei Bedarf und Interesse seinen Kopf reinstecken kann.“ Für ihn ist nicht nur die aktive Beteiligung am digitalen Austausch relevant, sondern auch die, wie er sie nennt, „Berieselung“ durch fremde und bekannte Kontakte mit Gedanken, Videos, Texten und Bildern.</p>

                <p>Er selbst schreibt auch ein Weblog, in dem er private Gedanken und Empfehlungen veröffentlicht. Als ich ihn gefragt habe, ob er es auch nutze, um eine Art Tagebuch zu führen, antwortete er: „Ich schreibe immer mal wieder Blogeinträge, die ich dann einfach nicht poste. Die bleiben dann in den Entwürfen liegen, und einige Zeit später finde ich sie und denke: Oh je, was war denn da los.“ Es geht ihm also nicht zwangsweise um die Veröffentlichung seiner Texte, sondern um die Tatsache, dass er durch sein Blog an ein Netz geknüpft ist, in dem er jederzeit veröffentlichen könnte, wenn er wollte. Die Selbstpublikation im Internet habe ich mit einer Grundfrage ins Gespräch gebracht: Ab wann macht es für meine Teilnehmer überhaupt Sinn, etwas im Internet und sozialen Netzwerken zu teilen? </p>

                <h4 id="die_sinnhaftigkeit_des_teilens">Die Sinnhaftigkeit des Teilens</h4>

                <p>Die wenigsten meiner Interviewpartner teilen wirklich private Dinge. Miriam sagt sogar, sie würde alles, was gefühlsduselig oder irgendwie anrüchig und unseriös ist, sofort entfernen oder schon gar nicht erst posten. Jan-Christopher und Dominic teilen auf Facebook nur Dinge, die sie auch in größeren Freundeskreisen erzählen würden oder die sie generell für amüsant und erzählenswert halten. Für Juliane ist es komplizierter: „Ich weiß nicht, wie ich was wem mitteilen will. Es gibt Dinge, die ich nicht mal in einem Gespräch erwähnen wollte, und die ich dann trotzdem einer Gruppe mitteilen will. Aber dann Frage ich mich: Was denken die Leute dann darüber? Das endet in der Regel dann damit, dass ich es gar nicht teile, weil mir der Gedankengang zu kompliziert ist.“ Das zeigt, dass schon die Reflexion darüber, was teilenswert sein könnte, zwangsweise mit Selbstreflexion einhergeht. Die Schnittstelle zum digitalen Netz zwingt uns, uns selbst zu hinterfragen und uns in einen Kontext zu stellen.</p>

                <p>Diese Kontextualisierung, die Ann-Kathrin zu Beginn des Kapitels als „Kommunikationszusammenhang“ beschreibt, beeinflusst auch das Beibehalten der Authentizität unserer eigenen Persönlichkeit. Vorhin haben wir festgestellt, dass die meisten digitalen Identitätsbilder lediglich Fragmente der tatsächlichen Persönlichkeit sind – was allerdings nur bedingt mit Gross, Hitzler und Honer und ihrer Theorie der „Bastelmentalität“ übereinstimmt, als vielmehr einfach die Idee Misochs der multiplen Identitätsentwürfe plausibilisiert. </p>

                <h4 id="authentizitt_durch_sprache_und_schrift">Authentizität durch Sprache und Schrift</h4>

                <p>Treten wir nun mit Maschinen und dadurch auch mit Menschen in Verbindung, geben wir uns selbst durch Medien wieder – sei es in Form von Text, Bild, Sprache oder sogar in Form von Videochats – die wiederum nur Fragmente unseres Ichs bestimmen. Dominic stört sich daran: „Ich habe Freunde, bei denen ich merke, dass sie viel lieber in Schriftform kommunizieren, und mich stört das, weil ich dabei einfach 95 Prozent des Gesprächs aufgrund fehlender Körpersprache oder Stimme nicht erfassen kann. Emoji-Icons machen das auch nicht wieder gut.“ Gleichzeitig hat Dominic beim Schreiben von Nachrichten, SMS, E-Mails und Chats einen eigenen Schreibstil entwickelt, der angeblich nicht identisch mit seinem Sprachstil, aber dennoch durchdacht und authentisch sei. Juliane kommuniziert viel über E-Mail und beschreibt ihren Stil bei Kurznachrichten als sehr funktional. Videochats nutzt sie selten, was aber lediglich an der schlechten Qualität der Videoübertragung liege. Ein gutes Beispiel für digitale Authentizität bringt Miriam mit ihrer frühen MySpace-Aktivität: „Damals auf MySpace war es schon plausibel, dass man sich, wenn man sich sehr gut kennen gelernt hatte, auch mal getroffen hat. (…) Meinen allerbesten Freund habe ich auch damals auf MySpace kennen gelernt.“ Miriam hat ihr MySpace-Profil sehr gepflegt und auf aktuellem Stand gehalten, und sich dadurch vermutlich auch sehr entsprochen. Auf Facebook tut sie das nicht mehr – „MySpace war damals ja dafür gedacht, neue Leute kennen zu lernen. Die Architektur ist heute in neuen Netzwerken ganz anders, das ist bei Facebook ja schon allein durch den Klarnamen nicht mehr so. Ich benutze es nur, um mit Leuten in Kontakt zu bleiben, die ich schon kenne. MySpace war also für neue Kontakte, Facebook ist da, um dann in Kontakt zu bleiben.“</p>

                <p>Die eigene Selbstwahrnehmung und das daraus resultierende Identitätsbild im und durch das Web zu kommunizieren wird also durch diverse Parameter bestimmt: Zum Einen ist die eigens gewählte Verfügbarkeit des Selbst im Internet von Bedeutung – inwieweit lasse ich überhaupt zu, dass ein Abbild von mir im digitalen Raum entsteht? In wie weit profitiere ich vom digitalen Abbild anderer? Auffindbarkeit in Suchmaschinen spielt hierbei eine wichtige Rolle. Ein weiterer Parameter ist die Positionierung im Web durch das Teilen von Neuigkeiten, Medien und Meinungen – gleichzeitig die möglichen Auswirkungen und Feedback zu geteilten Inhalten. Zuletzt spielt noch die Form der Kommunikation selbst eine Rolle: Das Vorhandensein von Authentizität im Kontakt mit Anderen.</p>
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>

                <h3 id="fazit">Fazit: Schnittmengen und Gegensätze</h3>

                <p>Im Laufe der Gespräche und in der anschließenden Auswertung der Interviews wurde klar, dass die Teilnehmer zwischen verschiedenen Polen hin und her schwirren: Authentizität der eigenen Persönlichkeit und Deckungsgleichheit mit dem analogen Ich sind ebenso relevant wie die Fragmentierung der Identität durch digitale Kanäle und die Wahrung der Anonymität. Unreflektiert im Bezug auf die eigene Selbstdarstellung war keiner der Teilnehmer; alle haben klare Positionen gefunden. Meine drei männlichen Gesprächspartner stehen dem Thema eher locker und unbesorgt gegenüber, während die drei jungen Frauen sehr behutsam und sicherheitsbedacht an die Identitätsprojektion herangehen. Negativ fällt fast allen Teilnehmern auf, dass ihnen das digitale Vertreten-sein viel Zeit raubt, und Abgelenktheit keine Eigenschaft ist, die sie sich an egal welcher ihrer Selbstbilder wünschen. </p>

                <p>Die Selbstwahrnehmung im Internet passiert auf einer gleichmäßigen Bewusstseinsebene aller Teilnehmer, ihr Ausdruck in Form von Selbstdarstellung wird aber auf unterschiedlich intensive Weise betrieben. Paul und Dominic beispielsweise sprechen überhaupt nicht mehr von „Selbstdarstellung“, weil der digitale Raum für sie so sehr Werkzeug des Alltags geworden ist, dass sie ihr Selbst nicht als Projektion, sondern lediglich als Spiegelbild und „Gliedmaß“ annehmen. Ann-Kathrin und Miriam neigen im Gegensatz dazu zu einer Positionierung und mehr oder weniger ausgeprägten Inszenierung, und machen dabei Gebrauch der Reflexion, die mit Schatten arbeitet und daher gewisse Fragmente ausspart. Außerdem knüpfen alle ihre digitale Identität sehr stark an ihre analoge Identität, in dem sie es beispielsweise großteils vermeiden oder zumindest bemerken, wenn „Identitätsleichen“ (ein Begriff, der von Paul und Ann-Kathrin benutzt wurde), also ungenutzte Profile und Accounts, von ihnen im Internet herumliegen.</p>

                <p>Trotz einiger Unterschiede in den Aussagen ist ihnen allen gemein, dass der digitale Raum Werkzeuge für sie bereit stellt, die sie in ihrer Selbstwahrnehmung und Selbstinszenierung unterstützten, und ihnen – wenngleich es einigen Gesprächspartnern nicht ganz bewusst war – erweiterte Möglichkeiten zur Selbstdarstellung im Internet gibt. Die Schnittstelle zur Technologie übermittelt diese Werkzeuge, und sie tut es mittlerweile so menschlich und gewohnt, dass man ihr besondere Aufmerksamkeit schenken muss, um sie nicht zu übersehen. </p>
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>
            </section> <!-- // section 4 -->

            <section id="seven">
                <h2 id="das-interface-als-uebermittler">Das Interface als Übermittler</h2>

                <h3 id="aussagen-der-teilnehmer">Aussagen der Teilnehmer</h3>

                <p class="first">Meine Interview-Partnerin Ann-Kathrin war die einzige Teilnehmerin, die von sich aus Bezug auf technologische und digitale Schnittstellen genommen hat. Als wir über die Systemunterschiede von Mac OS und Microsoft Windows gesprochen haben, beschreibt sie sich als typische Apple-Nutzerin: „Ich will einen Rechner, der mir mir seinem Interface signalisiert: Ich bin durchsichtig, man kann mich verstehen.“ Interessanter Weise führt Jan-Christopher unabhängig vom Themenkomplex der Interface-Gestaltung das Phänomen des „glasklaren Bürgers“ auf – stellt also unbewusst Mensch und Computer (Interface) anhand der Aussage Ann-Kathrins gegenüber. Das moderne Interface eines Betriebssystems hat den Anspruch, glasklar zu kommunizieren, welche Prozesse passieren, während der Mensch durch das Einspeisen von Informationen, Handlungen und Eigenschaften in ebendieses Interface glasklar wird. Dieser Gedankensprung sei in seiner Relevanz dahin gestellt, die Analogie ist allerdings erwähnenswert. Ann-Kathrin sagt außerdem zu modernen Technologien, die sich mit dem Begriff smart auf dem Markt positionieren und durch Algorithmen Alltagsprozesse optimieren sollen: „Es ist ja gar nicht so smart, der Smartness der Technologie ausgeliefert zu sein. Generell darf einfach die Reflexion nie ausbleiben. Gerade das passiert aber eben auch durch die zunehmend intuitiver werdenden Oberflächen. Die machen uns in einer gewisser Weise auch taub.“</p>
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>

                <h3 id="ideen-zum-interface-design">Ideen zum Interface Design</h3>

                <p class="first">Taub werden will niemand bei der Benutzung technischer Geräte – wünschenswert sind natürlich stets ein wacher Geist und Reflexion der eigenen Handlung beim Benutzen der digitalen Werkzeuge. Werkzeug als Synonym für Interface zu verwenden macht im heutigen Fall wieder Sinn: Während digitale Oberflächen lange Zeit emotionslos und unnatürlich waren, erhielten sie, wie zu Beginn erwähnt, durch superrealistisches Design zu Beginn des 21. Jahrhunderts einen Aufschwung; wurden extrem freundlich und handhabbar und nun, nur zehn Jahre später, haben wir uns bereits so intensiv an sie gewöhnt, dass wir sie in den meisten Fällen nicht mal mehr bemerken und ihre Gestaltung auch so konzipieren, dass das Interface „verschwindet“. Diese von Ann-Kathrin als intuitiv bezeichnete Form der Usability (beispielsweise durch Touchscreens und Gesten) ist in Form von Smartphones, Tabletcomputern, Netbooks und intelligenten Homesystemen stark in unseren Alltag integriert.</p>

                <p>Die Art, wie sich ein Medium gibt, also wie es aussieht und gestaltet ist, ist die eine Seite der Medaille. Auf der anderen Seite befindet sich die Art und Weise der Rückwirkung dieser Interfaces, die zur Selbstwahrnehmung im digitalen Raum beiträgt. Erinnern wir uns an die Microsoft Kinect, die als Interface vollkommen durchsichtig war und den digitalen Raum in den analogen Raum geschmolzen hat, und vergleichen wir diese Art von Technologien beispielsweise mit direkten graphischen Oberflächen wie dem Betriebssystems eines Smartphones (die allesamt dieser Tage noch mäßig funktionierend mit Sprachsteuerung ausgestattet sind), wird deutlich, dass sich beide Schnittstellen nicht vollkommen natürlich anfühlen. Das Touch-Display bedingt den Fokus auf einen Screen, der vergleichsweise klein ist und auch nur mit Fingern, nicht mit kommunikativen Gesten gesteuert werden kann. Die Kommunikation des Selbst wird damit wieder in Formate gepresst und verzerrt. Drahtlose, körpererkennende Technologien funktionieren momentan, weil der Betrachter in einer Art Spiel-Modus steckt, in dem er von vornherein nicht in Betracht zieht, authentisch zu handeln. Das Fraunhofer-Institut für Integrierte Schaltungen (IIS) hat mit ihrem Produkt Shore eine Software entwickelt, die eine minimale Barriere in die Verschmelzung des analogen und digitalen Raumes zieht: Sie entschlüsselt ohne haptisches, berührbares Interface (lediglich durch eine Webcam) die Gesichtsausdrücke der Betrachter und misst beispielsweise Alter, Geschlecht und Stimmung, und stellt diese mit Balkendiagrammen dar. Die Anwendung wurde mitunter für Spiele entwickelt; ihre rohe Fassung lässt aber zu, die Erkenntnisse der Maschine genau zu analysieren und durch Grimassen oder andere äußere Merkmale bewusst zu verfälschen. Dieses Bewusstsein beim gegenüberstehen solcher Maschinen ist im Normalfall nicht gegeben und führt dazu, dass sich die Betrachter viel stärker eingeschüchtert fühlen in ihrem Auftreten vor dem digitalen Spiegel.</p>
                
                <figure>
                    <img class="fraunhofer" src="media/fraunhofer.jpg" alt="Fraunhofer">
                    <figcaption>Die Software „Shore“ des Fraunhofer Instituts. Bild: <a href="http://www.iis.fraunhofer.de/" target="_blank">www.iis.fraunhofer.de</a></figcaption>
                </figure>
                
                <p>Der Grad an maschineller Durchsichtigkeit und emotionaler Gestaltung eines Interfaces kann meiner Meinung nach nicht exakt benannt werden. Wie schon festgestellt ist etwa die Videospielwelt eine vollkommen andere als die Selbstpräsenz auf sozialen Netzwerken oder gar privaten Homepages. Die Ich-Gestaltung hängt vom Anwender ab; seinen Bedürfnissen und Prinzipien, und die entscheiden auch, zu welche Schnittstellen der Nutzer tendiert. Eine zukünftige Auflösung der graphischen Oberflächen ist nur in so fern zu erwarten, als dass sie nicht verschwinden, aber sich noch intensiver in unseren Alltag weben und so natürlich und emotional werden, dass wir sie nicht als Fremdkörper wahrnehmen, und somit auch charakterlich nicht oder sehr absichtlich verzerrt mit ihnen umgehen können.</p>
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>
            </section> <!-- // section 5 -->

            <section id="eight">
                <h2 id="schluss">Schluss</h2>

                <h3>„Online“ als verbleichendes Präfix</h3>

                <p>Die Interviews, deren Aussagen leider nicht alle Platz gefunden haben in diesem Text, haben gezeigt, dass schon jetzt eine große Absicht beim Projizieren der Identität in den digitalen Raum herrscht. Es bleibt abzuwarten, was passiert, wenn sich unser Alltag nicht in einer Verkettung des analogen und digitalen Raumes abspielt, sondern in einer tatsächlichen Verschmelzung und neuen Realität, die Digitalität und Analogität vereint. Nimmt das Bewusstsein durch die intuitiveren technischen Schnittstellen ab, oder gewinnt es an Bedeutung? </p>

                <p>Durch die Gespräche mit den Nutzern und das eigene Treibenlassen der Gedanken habe ich festgestellt, dass das Thema extrem vielschichtig ist. Identität an sich ist schon ein komplexer Begriff; übertragen auf die digitale Welt scheint sich daraus ein fast unüberschaubares Gespann aus Theorien, Möglichkeiten und Veränderungen zu formen – so unüberschaubar, dass ich an manchen Punkten ins Grübeln geriet, ob es nicht sogar ein Fehler sein könnte, die „digitale Identität“ als solche zu benennen. Womöglich ist es schon fehlerhaft, es überhaupt in Betracht zu ziehen, dass es eine Parallelwelt zur analogen, physischen Welt geben kann, die neuer und anders wertvoll ist als die materiellen Orte, an denen wir uns befinden. Ich habe die Vermutung, dass sämtliche Analysen zur digitalen Realität mit der Zeit verbleichen werden, ebenso wie das Präfix „digital“ selbst.</p>

                <p>Dennoch befinden wir uns in einem Wandel, der analysiert und beobachtet sein will, über den philosophiert und recherchiert werden will. Ich habe dies mit meiner Bachelor-Arbeit aus der Perspektive eines Designers für die Schnittstellen untersucht, die ebendiesen Wandel beeinflussen können. Projektion der eigenen Identität, Rückprojektion der Maschinen, Positionierung im digitalen Raum, Anonymität, und Intuitivität der Interfaces sind leider nur einige wenige Aspekte, über die es nachzudenken gilt. Ich hoffe, mit diesem Text einerseits eine aktuelle Position der jungen Generation im digitalen Raum gezeichnet zu haben, und andererseits, einige Denkanstöße zur eignen Selbstwahrnehmung im Netz geben zu können.</p>
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>
                
                <h3>Fußnoten</h3>
                
                <ol class="footnotes">
                    <li id="footnote_01">Beispielhaft sind Science-Fiction-Filme wie Minority Report (Regie: Steven Spielberg, 2002), die schon in der Genre-Bezeichnung (Science = engl. Wissenschaft; engl. fiction = fiktiv, nicht real) darauf aus sind, utopische Ideen zu visualisieren. <a href="#footnote_1">&rarr; Zurück zum Text.</a></li>
                    <li id="footnote_02">Die Heterotopie ist eine von Michel Focault (1926 – 1984) verwendete Beschreibung für Orte, die bestimmte gesellschaftliche oder anderweitig definierte Normen nicht oder nur teilweise erfüllen. Während sich Focault damals (1967) eher mit physischen Heterotopien beschäftigt, kann diese Idee auch auf digitale Räume übertragen werden – beispielsweise auf Chatrooms oder Rollenspiele. <a href="#footnote_2">&rarr; Zurück zum Text.</a></li>
                    <li id="footnote_03">Die Nintendo Wii wird seit 2006 von Nintendo vertrieben und war die erste Art von Konsole, der ein großen Markterfolg im Bereich der dreidimensional steuerbaren Interfaces gelang. Die Microsoft Kinect wird seit November 2010 von Microsoft Windows hergestellt und dient zur Steuerung der Videospielkonsole Xbox 360. <a href="#footnote_3">&rarr; Zurück zum Text.</a></li>
                    <li id="footnote_04">Rudolf Pannwitz erwähnt in seinem Buch Die Krise der europäischen Kultur erstmals den „postmodernen Menschen“. Der Begriff Postmoderne bezog sich anfänglich auf offensivere Kunstformen im zweiten Teil des 20. Jahrhunderts. <a href="#footnote_4">&rarr; Zurück zum Text.</a></li>
                    <li id="footnote_05">Ein MUD (Multi-User-Domain bzw. Multi-User-Dungeon) bezeichnet eine frühe Form des Raums für digitale Rollenspiele, die meist auf Text basierten. Anhand von Fenstern war es möglich, in verschiedenen MUDs gleichzeitig zu agieren (vgl. Turkle 1998). <a href="#footnote_5">&rarr; Zurück zum Text.</a></li>
                </ol>
                <p class="last"></p>
            </section> <!-- // section 6 -->
            
            <section id="nine">
                <h2 id="literaturverzeichnis">Literaturverzeichnis</h2>
                
                <p><strong>Hemmerling, Marco:</strong> „Die Erweiterung der Realität“ in <em>Augmented Reality – Mensch, Raum und Virtualität,</em> herausgegeben von Marco Hemmerling. München 2011.</p>

                <p><strong>Milgram, Paul, u.a.:</strong> „Augmented Reality: A class of displays on the reality-virtuality continuum“ in <em>Proceedings of Telemanipulator and Telepresence Technologies.</em> 1994.</p>

                <p><strong>Misoch, Sabina:</strong> „Identitäten im Internet“, Dissertation der Universität Karlsruhe. Konstanz 2004.
                Mummenday, Hans Dieter: <em>Psychologie der Selbstdarstellung.</em> Göttingen 1995</p>

                <p><strong>Gross, Peter; Hitzler, Ronald; Honer, Anne:</strong> <em>Kleine Konstruktionen – Zur Theorie der Bastel-Mentalität.</em> Manuskript, Bamberg 1985.</p>

                <p><strong>Turkle, Sherry:</strong> <em>Leben im Netz.</em> Reinbeck 1998.</p>

                <p><strong>Bolter, David J.; Grusin, Richard:</strong> <em>Remediation – Understanding New Media.</em> Massachusetts 1999.</p>

                <p><strong>DIVSI</strong> (Deutsches Institut für Vertrauen und Sicherheit im Internet): <a href="https://www.divsi.de/sites/default/files/presse/docs/DIVSI-Milieu-Studie_Kurzfassung.pdf" target="_blank"><em>DIVSI Milieu-Studie zu Vertrauen und Sicherheit im Internet.</em></a> Hamburg 2011.</p>
                
                <p class="last"><span class="backtotop"><a href="#ihv_start" class="scroll">Zurück nach oben &#8630;</a></span></p>
            </section>
            
            <footer>
                <p class="meta">Die vorliegende Arbeit ist selbstständig und ohne Benutzung anderer als der angegebenen Hilfsmittel von mir angefertigt worden; die aus fremden Quellen direkt oder indirekt übernommenen Gedanken sind als solche kenntlich gemacht. Die Arbeit wurde bisher in gleicher oder ähnlicher Form keiner anderen Prüfungskommission vorgelegt und auch nicht veröffentlicht. Christoph Rauscher, Stand: 8. Januar 2013.</p>
                <p class="meta"><a href="http://christophrauscher.de">Christoph Rauscher</a> &copy; <?php echo date("Y"); ?></p>
            </footer>
        </div>
        
    </div> <!-- // container -->
    
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-6347422-4']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
</body>

</html>
